name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: my-app
  CLUSTER_NAME: mycluster
  ACR_NAME: xptoacr
  IMAGE_NAME: myapp
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build Docker image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
        docker login $ACR_NAME.azurecr.io -u $ACR_NAME -p ${{ secrets.ACR_PASSWORD }}
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: $RESOURCE_GROUP
        cluster-name: $CLUSTER_NAME
    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        images: $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
        namespace: default
        manifests: |
          myapp.yaml